#!/usr/bin/env bash
set -eufo pipefail
npm out --long
npm whoami
npm run build
transcribe --heading-level 4 --url "https://github.com/fluture-js/fluture-sanctuary-types/blob/v${VERSION?Environment variable not set}/{filename}#L{line}" index.mjs > README.md
git add README.md
